// @desc    Upload a file to the cloud and get the URL back
// @route   POST /api/upload
const uploadFile = async (req, res) => {
    try {
        // If no file was sent from the frontend
        if (!req.file) {
            return res.status(400).json({ message: 'No file was provided.' });
        }

        // 'req.file.path' is the magic secure URL generated by Cloudinary!
        res.status(200).json({
            message: 'File uploaded successfully!',
            file_url: req.file.path
        });

    } catch (error) {
        console.error('Error in uploadFile:', error);
        res.status(500).json({ message: 'Server Error during file upload.' });
    }
};

// @desc    Upload multiple files to the cloud and get their URLs
// @route   POST /api/upload/multiple
const uploadMultipleFiles = async (req, res) => {
    try {
        // Notice we use req.files (plural) here!
        if (!req.files || req.files.length === 0) {
            return res.status(400).json({ message: 'No files were provided.' });
        }

        // We loop through the array of files and grab the magic Cloudinary URL for each one
        const fileUrls = req.files.map(file => file.path);

        res.status(200).json({
            message: `${req.files.length} files uploaded successfully!`,
            file_urls: fileUrls // This returns an array of links [ "link1", "link2" ]
        });

    } catch (error) {
        console.error('Error in uploadMultipleFiles:', error);
        res.status(500).json({ message: 'Server Error during multiple file upload.' });
    }
};

module.exports = { uploadFile, uploadMultipleFiles };